version: '3.3'
services:
  wireguard_client:
    image: ghcr.io/linuxserver/wireguard
    container_name: wireguard_client
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Copenhagen
      - VPN_PROTOCOL=wireguard
      - AUTOCONNECT=true
      - PIA_USER= #fill-in
      - PIA_PASS= #fill-in
    ports:
      - 9091:9091/tcp
    volumes:
      - ./volumes/config:/config
      - /lib/modules:/lib/modules
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv6.conf.default.disable_ipv6=1
    restart: unless-stopped
  transmission:
    image: ghcr.io/linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Copenhagen
      - TRANSMISSION_WEB_HOME=/combustion-release/
      - USER=transmission
      - PASS=transmission
    volumes:
      - ./volumes/config:/config
      - ./volumes/downloads:/downloads
      - ./volumes/watch:/watch
    network_mode: "service:wireguard_client"
    depends_on: [ "wireguard_client", ]
    restart: unless-stopped
